[defaults]
exfat_defaults=uid=$UID,gid=$GID
exfat_allow=uid=$UID,gid=$GID,dmask,fmask
vfat_defaults=uid=$UID,gid=$GID
vfat_allow=uid=$UID,gid=$GID,dmask,fmask
ntfs_defaults=uid=$UID,gid=$GID
ntfs_allow=uid=$UID,gid=$GID
